# Generated by Django 3.1.2 on 2020-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
    ]
