# Generated by Django 3.1.2 on 2020-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='kitchens',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
    ]
